language: node_js

sudo: required

services:
  - docker
  
addons:
  sonarcloud:
    organization: "andryfailli-github"
    token:
      secure: $SONAR_TOKEN
    github_token:
      secure: $GITHUB_TOKEN
    branches:
      - master
      - develop
      - feature/*
      - hotfix/*
      - release/*
  
node_js:
  - "6"
    
jdk:
  - oraclejdk8

script:
  - mvn clean test verify package sonar:sonar
  - cat ./coverage/coverage.lcov | ./node_modules/coveralls/bin/coveralls.js
  
cache:
  directories:
    - "node_modules"
    - '$HOME/.sonar/cache'